server: 
  port: 8090
# druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ppmall?characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: zxcvbnm
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  # redis
  redis:
    host:  127.0.0.1
    port: 6379
    password: zxcvbnm
    database: 0
    pool:
      max-active: 8
      min-idle: 1
      max-idle: 1
      max-wait: -1
# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  #type-aliases-package: com.winter.model

# pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
# actuator
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
# logback
logging: 
  config: classpath:logback-boot.xml

